### PR TITLE
chore: polkadot v1.12.0

### PR DESCRIPTION
**Pull request by Daanvdplas**

### CODE REVIEW

**Review by al3mart — APPROVED** [review]
Looking good.

I think it could be useful to include https://github.com/paritytech/polkadot-sdk/pull/3872 but we can tackle in a different pr :ok_hand:

**Comment by evilrobot-01** [comment]
Please can the merge conflicts be resolved after v1.11 merged.

**Comment by Daanvdplas** [comment]
>Please can the merge conflicts be resolved after v1.11 merged.

@al3mart will do this today

**Comment by al3mart** [comment]
This should be ready for final review / merge. But let's get #29 merged first.

**Review by AlexD10S — APPROVED** [review]
LGTM! But let's wait to merge until `assets-parachain` and `contracts-parachain` are at `v1.11.0`

**Pull request merged**
